### ISSUE TITLE
How many orchids?

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-sensitive-species-data-generalization#10]
Near the end of [§1.2](https://docs.gbif-uat.org/sensitive-species-data-generalization/en/#list-complementarity), the text mentions more than 34,000 species in Orchidaceae.

At the start of [§2.2.2](https://docs.gbif-uat.org/sensitive-species-data-generalization/en/#generalization-examples-orchids), we have "Orchids are one of the largest families of flowering plants with nearly 30,000 species globally…"

Can we choose one assertion to use both places?

**Comment by andrewrodrigues** [comment]
Kew plants of the world online  has 31,068 accepted orchid species names - https://powo.science.kew.org/results?f=accepted_names%2Cspecies_f&q=Orchidaceae

**Comment by kcopas** [comment]
Thank you!

**Comment by kcopas** [comment]
Oh, ok, the plot thickens:
> For CITES-listed species, 84.6 per cent are plants although this may be due to the fact that two large plant taxa are included in the CITES-lists, notably Orchidaceae (34,354 species).

Reckon that's a combination of accepted, synonymized and what-have-you?

**Comment by kcopas** [comment]
Maybe "more than 31,000" can get us out of this jam…? I think references are limited to the narrative, so we won't get hung up on the particulars, and CITES can have what they have…

**Comment by franastorga** [comment]
I would keep it as: 
"Orchids are one of the largest families of flowering plants with more than 31,000 accepted species (cite https://powo.science.kew.org/results?f=accepted_names%2Cspecies_f&q=Orchidaceae). Orchid species are globally and commonly traded, being particularly vulnerable to over-harvest because many species have a limited range and/or occur at low densities ([Hinsley et al. 2016](https://doi.org/10.1111/cobi.12721); [Hinsley et al. 2018](https://doi.org/10.1093/botlinnean/box083); [Fay 2018](https://doi.org/10.1186/s40529-018-0232-z)). "

**Comment by kcopas** [comment]
Substituted [Orchidaceae family page](https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:30000046-2) for the search result above.
